language: php

php:
  - 7.2
  - 7.3
  - 7.4

os: linux

jobs:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - composer test

notifications:
  email: false
